// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes.proto

package meetup.beeno;

public final class HDataTypes {
  private HDataTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DateTimeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional string timezone = 2;
    boolean hasTimezone();
    String getTimezone();
  }
  public static final class DateTime extends
      com.google.protobuf.GeneratedMessage
      implements DateTimeOrBuilder {
    // Use DateTime.newBuilder() to construct.
    private DateTime(Builder builder) {
      super(builder);
    }
    private DateTime(boolean noInit) {}
    
    private static final DateTime defaultInstance;
    public static DateTime getDefaultInstance() {
      return defaultInstance;
    }
    
    public DateTime getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meetup.beeno.HDataTypes.internal_static_hbase_DateTime_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meetup.beeno.HDataTypes.internal_static_hbase_DateTime_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional string timezone = 2;
    public static final int TIMEZONE_FIELD_NUMBER = 2;
    private Object timezone_;
    public boolean hasTimezone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTimezone() {
      Object ref = timezone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timezone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimezoneBytes() {
      Object ref = timezone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timezone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      timestamp_ = 0L;
      timezone_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimezoneBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimezoneBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.DateTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.DateTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(meetup.beeno.HDataTypes.DateTime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements meetup.beeno.HDataTypes.DateTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return meetup.beeno.HDataTypes.internal_static_hbase_DateTime_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return meetup.beeno.HDataTypes.internal_static_hbase_DateTime_fieldAccessorTable;
      }
      
      // Construct using meetup.beeno.HDataTypes.DateTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        timezone_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return meetup.beeno.HDataTypes.DateTime.getDescriptor();
      }
      
      public meetup.beeno.HDataTypes.DateTime getDefaultInstanceForType() {
        return meetup.beeno.HDataTypes.DateTime.getDefaultInstance();
      }
      
      public meetup.beeno.HDataTypes.DateTime build() {
        meetup.beeno.HDataTypes.DateTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private meetup.beeno.HDataTypes.DateTime buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        meetup.beeno.HDataTypes.DateTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public meetup.beeno.HDataTypes.DateTime buildPartial() {
        meetup.beeno.HDataTypes.DateTime result = new meetup.beeno.HDataTypes.DateTime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timezone_ = timezone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof meetup.beeno.HDataTypes.DateTime) {
          return mergeFrom((meetup.beeno.HDataTypes.DateTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(meetup.beeno.HDataTypes.DateTime other) {
        if (other == meetup.beeno.HDataTypes.DateTime.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasTimezone()) {
          setTimezone(other.getTimezone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              timezone_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string timezone = 2;
      private Object timezone_ = "";
      public boolean hasTimezone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTimezone() {
        Object ref = timezone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timezone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimezone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timezone_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimezone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timezone_ = getDefaultInstance().getTimezone();
        onChanged();
        return this;
      }
      void setTimezone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        timezone_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hbase.DateTime)
    }
    
    static {
      defaultInstance = new DateTime(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hbase.DateTime)
  }
  
  public interface JavaEnumOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string type = 1;
    boolean hasType();
    String getType();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class JavaEnum extends
      com.google.protobuf.GeneratedMessage
      implements JavaEnumOrBuilder {
    // Use JavaEnum.newBuilder() to construct.
    private JavaEnum(Builder builder) {
      super(builder);
    }
    private JavaEnum(boolean noInit) {}
    
    private static final JavaEnum defaultInstance;
    public static JavaEnum getDefaultInstance() {
      return defaultInstance;
    }
    
    public JavaEnum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meetup.beeno.HDataTypes.internal_static_hbase_JavaEnum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meetup.beeno.HDataTypes.internal_static_hbase_JavaEnum_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.JavaEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(meetup.beeno.HDataTypes.JavaEnum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements meetup.beeno.HDataTypes.JavaEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return meetup.beeno.HDataTypes.internal_static_hbase_JavaEnum_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return meetup.beeno.HDataTypes.internal_static_hbase_JavaEnum_fieldAccessorTable;
      }
      
      // Construct using meetup.beeno.HDataTypes.JavaEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return meetup.beeno.HDataTypes.JavaEnum.getDescriptor();
      }
      
      public meetup.beeno.HDataTypes.JavaEnum getDefaultInstanceForType() {
        return meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance();
      }
      
      public meetup.beeno.HDataTypes.JavaEnum build() {
        meetup.beeno.HDataTypes.JavaEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private meetup.beeno.HDataTypes.JavaEnum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        meetup.beeno.HDataTypes.JavaEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public meetup.beeno.HDataTypes.JavaEnum buildPartial() {
        meetup.beeno.HDataTypes.JavaEnum result = new meetup.beeno.HDataTypes.JavaEnum(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof meetup.beeno.HDataTypes.JavaEnum) {
          return mergeFrom((meetup.beeno.HDataTypes.JavaEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(meetup.beeno.HDataTypes.JavaEnum other) {
        if (other == meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string type = 1;
      private Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hbase.JavaEnum)
    }
    
    static {
      defaultInstance = new JavaEnum(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hbase.JavaEnum)
  }
  
  public interface StringListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string values = 1;
    java.util.List<String> getValuesList();
    int getValuesCount();
    String getValues(int index);
  }
  public static final class StringList extends
      com.google.protobuf.GeneratedMessage
      implements StringListOrBuilder {
    // Use StringList.newBuilder() to construct.
    private StringList(Builder builder) {
      super(builder);
    }
    private StringList(boolean noInit) {}
    
    private static final StringList defaultInstance;
    public static StringList getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meetup.beeno.HDataTypes.internal_static_hbase_StringList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meetup.beeno.HDataTypes.internal_static_hbase_StringList_fieldAccessorTable;
    }
    
    // repeated string values = 1;
    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList values_;
    public java.util.List<String>
        getValuesList() {
      return values_;
    }
    public int getValuesCount() {
      return values_.size();
    }
    public String getValues(int index) {
      return values_.get(index);
    }
    
    private void initFields() {
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(1, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.StringList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.StringList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(meetup.beeno.HDataTypes.StringList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements meetup.beeno.HDataTypes.StringListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return meetup.beeno.HDataTypes.internal_static_hbase_StringList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return meetup.beeno.HDataTypes.internal_static_hbase_StringList_fieldAccessorTable;
      }
      
      // Construct using meetup.beeno.HDataTypes.StringList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return meetup.beeno.HDataTypes.StringList.getDescriptor();
      }
      
      public meetup.beeno.HDataTypes.StringList getDefaultInstanceForType() {
        return meetup.beeno.HDataTypes.StringList.getDefaultInstance();
      }
      
      public meetup.beeno.HDataTypes.StringList build() {
        meetup.beeno.HDataTypes.StringList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private meetup.beeno.HDataTypes.StringList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        meetup.beeno.HDataTypes.StringList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public meetup.beeno.HDataTypes.StringList buildPartial() {
        meetup.beeno.HDataTypes.StringList result = new meetup.beeno.HDataTypes.StringList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(
              values_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof meetup.beeno.HDataTypes.StringList) {
          return mergeFrom((meetup.beeno.HDataTypes.StringList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(meetup.beeno.HDataTypes.StringList other) {
        if (other == meetup.beeno.HDataTypes.StringList.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureValuesIsMutable();
              values_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string values = 1;
      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      public int getValuesCount() {
        return values_.size();
      }
      public String getValues(int index) {
        return values_.get(index);
      }
      public Builder setValues(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addValues(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllValues(
          java.lang.Iterable<String> values) {
        ensureValuesIsMutable();
        super.addAll(values, values_);
        onChanged();
        return this;
      }
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addValues(com.google.protobuf.ByteString value) {
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:hbase.StringList)
    }
    
    static {
      defaultInstance = new StringList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hbase.StringList)
  }
  
  public interface HFieldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .hbase.HField.Type type = 1;
    boolean hasType();
    meetup.beeno.HDataTypes.HField.Type getType();
    
    // optional string text = 2;
    boolean hasText();
    String getText();
    
    // optional int64 integer = 3;
    boolean hasInteger();
    long getInteger();
    
    // optional double float = 4;
    boolean hasFloat();
    double getFloat();
    
    // optional bool boolean = 5;
    boolean hasBoolean();
    boolean getBoolean();
    
    // optional bytes binary = 6;
    boolean hasBinary();
    com.google.protobuf.ByteString getBinary();
    
    // optional .hbase.DateTime date_time = 7;
    boolean hasDateTime();
    meetup.beeno.HDataTypes.DateTime getDateTime();
    meetup.beeno.HDataTypes.DateTimeOrBuilder getDateTimeOrBuilder();
    
    // optional .hbase.JavaEnum java_enum = 8;
    boolean hasJavaEnum();
    meetup.beeno.HDataTypes.JavaEnum getJavaEnum();
    meetup.beeno.HDataTypes.JavaEnumOrBuilder getJavaEnumOrBuilder();
    
    // optional .hbase.StringList string_list = 9;
    boolean hasStringList();
    meetup.beeno.HDataTypes.StringList getStringList();
    meetup.beeno.HDataTypes.StringListOrBuilder getStringListOrBuilder();
  }
  public static final class HField extends
      com.google.protobuf.GeneratedMessage
      implements HFieldOrBuilder {
    // Use HField.newBuilder() to construct.
    private HField(Builder builder) {
      super(builder);
    }
    private HField(boolean noInit) {}
    
    private static final HField defaultInstance;
    public static HField getDefaultInstance() {
      return defaultInstance;
    }
    
    public HField getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meetup.beeno.HDataTypes.internal_static_hbase_HField_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meetup.beeno.HDataTypes.internal_static_hbase_HField_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      TEXT(0, 1),
      INTEGER(1, 2),
      FLOAT(2, 3),
      BOOLEAN(3, 4),
      BINARY(4, 5),
      DATETIME(5, 6),
      JAVAENUM(6, 7),
      STRINGLIST(7, 8),
      ;
      
      public static final int TEXT_VALUE = 1;
      public static final int INTEGER_VALUE = 2;
      public static final int FLOAT_VALUE = 3;
      public static final int BOOLEAN_VALUE = 4;
      public static final int BINARY_VALUE = 5;
      public static final int DATETIME_VALUE = 6;
      public static final int JAVAENUM_VALUE = 7;
      public static final int STRINGLIST_VALUE = 8;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return TEXT;
          case 2: return INTEGER;
          case 3: return FLOAT;
          case 4: return BOOLEAN;
          case 5: return BINARY;
          case 6: return DATETIME;
          case 7: return JAVAENUM;
          case 8: return STRINGLIST;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return meetup.beeno.HDataTypes.HField.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        TEXT, INTEGER, FLOAT, BOOLEAN, BINARY, DATETIME, JAVAENUM, STRINGLIST, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:hbase.HField.Type)
    }
    
    private int bitField0_;
    // required .hbase.HField.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private meetup.beeno.HDataTypes.HField.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public meetup.beeno.HDataTypes.HField.Type getType() {
      return type_;
    }
    
    // optional string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 integer = 3;
    public static final int INTEGER_FIELD_NUMBER = 3;
    private long integer_;
    public boolean hasInteger() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getInteger() {
      return integer_;
    }
    
    // optional double float = 4;
    public static final int FLOAT_FIELD_NUMBER = 4;
    private double float_;
    public boolean hasFloat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getFloat() {
      return float_;
    }
    
    // optional bool boolean = 5;
    public static final int BOOLEAN_FIELD_NUMBER = 5;
    private boolean boolean_;
    public boolean hasBoolean() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getBoolean() {
      return boolean_;
    }
    
    // optional bytes binary = 6;
    public static final int BINARY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString binary_;
    public boolean hasBinary() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getBinary() {
      return binary_;
    }
    
    // optional .hbase.DateTime date_time = 7;
    public static final int DATE_TIME_FIELD_NUMBER = 7;
    private meetup.beeno.HDataTypes.DateTime dateTime_;
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public meetup.beeno.HDataTypes.DateTime getDateTime() {
      return dateTime_;
    }
    public meetup.beeno.HDataTypes.DateTimeOrBuilder getDateTimeOrBuilder() {
      return dateTime_;
    }
    
    // optional .hbase.JavaEnum java_enum = 8;
    public static final int JAVA_ENUM_FIELD_NUMBER = 8;
    private meetup.beeno.HDataTypes.JavaEnum javaEnum_;
    public boolean hasJavaEnum() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public meetup.beeno.HDataTypes.JavaEnum getJavaEnum() {
      return javaEnum_;
    }
    public meetup.beeno.HDataTypes.JavaEnumOrBuilder getJavaEnumOrBuilder() {
      return javaEnum_;
    }
    
    // optional .hbase.StringList string_list = 9;
    public static final int STRING_LIST_FIELD_NUMBER = 9;
    private meetup.beeno.HDataTypes.StringList stringList_;
    public boolean hasStringList() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public meetup.beeno.HDataTypes.StringList getStringList() {
      return stringList_;
    }
    public meetup.beeno.HDataTypes.StringListOrBuilder getStringListOrBuilder() {
      return stringList_;
    }
    
    private void initFields() {
      type_ = meetup.beeno.HDataTypes.HField.Type.TEXT;
      text_ = "";
      integer_ = 0L;
      float_ = 0D;
      boolean_ = false;
      binary_ = com.google.protobuf.ByteString.EMPTY;
      dateTime_ = meetup.beeno.HDataTypes.DateTime.getDefaultInstance();
      javaEnum_ = meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance();
      stringList_ = meetup.beeno.HDataTypes.StringList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDateTime()) {
        if (!getDateTime().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasJavaEnum()) {
        if (!getJavaEnum().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, integer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, float_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, boolean_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, binary_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, dateTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, javaEnum_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, stringList_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, integer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, float_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boolean_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, binary_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, dateTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, javaEnum_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, stringList_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static meetup.beeno.HDataTypes.HField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.HField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static meetup.beeno.HDataTypes.HField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(meetup.beeno.HDataTypes.HField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements meetup.beeno.HDataTypes.HFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return meetup.beeno.HDataTypes.internal_static_hbase_HField_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return meetup.beeno.HDataTypes.internal_static_hbase_HField_fieldAccessorTable;
      }
      
      // Construct using meetup.beeno.HDataTypes.HField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDateTimeFieldBuilder();
          getJavaEnumFieldBuilder();
          getStringListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = meetup.beeno.HDataTypes.HField.Type.TEXT;
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        integer_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        float_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        boolean_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        binary_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (dateTimeBuilder_ == null) {
          dateTime_ = meetup.beeno.HDataTypes.DateTime.getDefaultInstance();
        } else {
          dateTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (javaEnumBuilder_ == null) {
          javaEnum_ = meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance();
        } else {
          javaEnumBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (stringListBuilder_ == null) {
          stringList_ = meetup.beeno.HDataTypes.StringList.getDefaultInstance();
        } else {
          stringListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return meetup.beeno.HDataTypes.HField.getDescriptor();
      }
      
      public meetup.beeno.HDataTypes.HField getDefaultInstanceForType() {
        return meetup.beeno.HDataTypes.HField.getDefaultInstance();
      }
      
      public meetup.beeno.HDataTypes.HField build() {
        meetup.beeno.HDataTypes.HField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private meetup.beeno.HDataTypes.HField buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        meetup.beeno.HDataTypes.HField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public meetup.beeno.HDataTypes.HField buildPartial() {
        meetup.beeno.HDataTypes.HField result = new meetup.beeno.HDataTypes.HField(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.integer_ = integer_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.float_ = float_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.boolean_ = boolean_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.binary_ = binary_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (dateTimeBuilder_ == null) {
          result.dateTime_ = dateTime_;
        } else {
          result.dateTime_ = dateTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (javaEnumBuilder_ == null) {
          result.javaEnum_ = javaEnum_;
        } else {
          result.javaEnum_ = javaEnumBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (stringListBuilder_ == null) {
          result.stringList_ = stringList_;
        } else {
          result.stringList_ = stringListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof meetup.beeno.HDataTypes.HField) {
          return mergeFrom((meetup.beeno.HDataTypes.HField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(meetup.beeno.HDataTypes.HField other) {
        if (other == meetup.beeno.HDataTypes.HField.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasInteger()) {
          setInteger(other.getInteger());
        }
        if (other.hasFloat()) {
          setFloat(other.getFloat());
        }
        if (other.hasBoolean()) {
          setBoolean(other.getBoolean());
        }
        if (other.hasBinary()) {
          setBinary(other.getBinary());
        }
        if (other.hasDateTime()) {
          mergeDateTime(other.getDateTime());
        }
        if (other.hasJavaEnum()) {
          mergeJavaEnum(other.getJavaEnum());
        }
        if (other.hasStringList()) {
          mergeStringList(other.getStringList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasDateTime()) {
          if (!getDateTime().isInitialized()) {
            
            return false;
          }
        }
        if (hasJavaEnum()) {
          if (!getJavaEnum().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              meetup.beeno.HDataTypes.HField.Type value = meetup.beeno.HDataTypes.HField.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              integer_ = input.readInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              float_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              boolean_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              binary_ = input.readBytes();
              break;
            }
            case 58: {
              meetup.beeno.HDataTypes.DateTime.Builder subBuilder = meetup.beeno.HDataTypes.DateTime.newBuilder();
              if (hasDateTime()) {
                subBuilder.mergeFrom(getDateTime());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDateTime(subBuilder.buildPartial());
              break;
            }
            case 66: {
              meetup.beeno.HDataTypes.JavaEnum.Builder subBuilder = meetup.beeno.HDataTypes.JavaEnum.newBuilder();
              if (hasJavaEnum()) {
                subBuilder.mergeFrom(getJavaEnum());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJavaEnum(subBuilder.buildPartial());
              break;
            }
            case 74: {
              meetup.beeno.HDataTypes.StringList.Builder subBuilder = meetup.beeno.HDataTypes.StringList.newBuilder();
              if (hasStringList()) {
                subBuilder.mergeFrom(getStringList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStringList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .hbase.HField.Type type = 1;
      private meetup.beeno.HDataTypes.HField.Type type_ = meetup.beeno.HDataTypes.HField.Type.TEXT;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public meetup.beeno.HDataTypes.HField.Type getType() {
        return type_;
      }
      public Builder setType(meetup.beeno.HDataTypes.HField.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = meetup.beeno.HDataTypes.HField.Type.TEXT;
        onChanged();
        return this;
      }
      
      // optional string text = 2;
      private Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
      }
      
      // optional int64 integer = 3;
      private long integer_ ;
      public boolean hasInteger() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getInteger() {
        return integer_;
      }
      public Builder setInteger(long value) {
        bitField0_ |= 0x00000004;
        integer_ = value;
        onChanged();
        return this;
      }
      public Builder clearInteger() {
        bitField0_ = (bitField0_ & ~0x00000004);
        integer_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double float = 4;
      private double float_ ;
      public boolean hasFloat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getFloat() {
        return float_;
      }
      public Builder setFloat(double value) {
        bitField0_ |= 0x00000008;
        float_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        float_ = 0D;
        onChanged();
        return this;
      }
      
      // optional bool boolean = 5;
      private boolean boolean_ ;
      public boolean hasBoolean() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getBoolean() {
        return boolean_;
      }
      public Builder setBoolean(boolean value) {
        bitField0_ |= 0x00000010;
        boolean_ = value;
        onChanged();
        return this;
      }
      public Builder clearBoolean() {
        bitField0_ = (bitField0_ & ~0x00000010);
        boolean_ = false;
        onChanged();
        return this;
      }
      
      // optional bytes binary = 6;
      private com.google.protobuf.ByteString binary_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBinary() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getBinary() {
        return binary_;
      }
      public Builder setBinary(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        binary_ = value;
        onChanged();
        return this;
      }
      public Builder clearBinary() {
        bitField0_ = (bitField0_ & ~0x00000020);
        binary_ = getDefaultInstance().getBinary();
        onChanged();
        return this;
      }
      
      // optional .hbase.DateTime date_time = 7;
      private meetup.beeno.HDataTypes.DateTime dateTime_ = meetup.beeno.HDataTypes.DateTime.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.DateTime, meetup.beeno.HDataTypes.DateTime.Builder, meetup.beeno.HDataTypes.DateTimeOrBuilder> dateTimeBuilder_;
      public boolean hasDateTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public meetup.beeno.HDataTypes.DateTime getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      public Builder setDateTime(meetup.beeno.HDataTypes.DateTime value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setDateTime(
          meetup.beeno.HDataTypes.DateTime.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeDateTime(meetup.beeno.HDataTypes.DateTime value) {
        if (dateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              dateTime_ != meetup.beeno.HDataTypes.DateTime.getDefaultInstance()) {
            dateTime_ =
              meetup.beeno.HDataTypes.DateTime.newBuilder(dateTime_).mergeFrom(value).buildPartial();
          } else {
            dateTime_ = value;
          }
          onChanged();
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          dateTime_ = meetup.beeno.HDataTypes.DateTime.getDefaultInstance();
          onChanged();
        } else {
          dateTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public meetup.beeno.HDataTypes.DateTime.Builder getDateTimeBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      public meetup.beeno.HDataTypes.DateTimeOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.DateTime, meetup.beeno.HDataTypes.DateTime.Builder, meetup.beeno.HDataTypes.DateTimeOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              meetup.beeno.HDataTypes.DateTime, meetup.beeno.HDataTypes.DateTime.Builder, meetup.beeno.HDataTypes.DateTimeOrBuilder>(
                  dateTime_,
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }
      
      // optional .hbase.JavaEnum java_enum = 8;
      private meetup.beeno.HDataTypes.JavaEnum javaEnum_ = meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.JavaEnum, meetup.beeno.HDataTypes.JavaEnum.Builder, meetup.beeno.HDataTypes.JavaEnumOrBuilder> javaEnumBuilder_;
      public boolean hasJavaEnum() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public meetup.beeno.HDataTypes.JavaEnum getJavaEnum() {
        if (javaEnumBuilder_ == null) {
          return javaEnum_;
        } else {
          return javaEnumBuilder_.getMessage();
        }
      }
      public Builder setJavaEnum(meetup.beeno.HDataTypes.JavaEnum value) {
        if (javaEnumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          javaEnum_ = value;
          onChanged();
        } else {
          javaEnumBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setJavaEnum(
          meetup.beeno.HDataTypes.JavaEnum.Builder builderForValue) {
        if (javaEnumBuilder_ == null) {
          javaEnum_ = builderForValue.build();
          onChanged();
        } else {
          javaEnumBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergeJavaEnum(meetup.beeno.HDataTypes.JavaEnum value) {
        if (javaEnumBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              javaEnum_ != meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance()) {
            javaEnum_ =
              meetup.beeno.HDataTypes.JavaEnum.newBuilder(javaEnum_).mergeFrom(value).buildPartial();
          } else {
            javaEnum_ = value;
          }
          onChanged();
        } else {
          javaEnumBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearJavaEnum() {
        if (javaEnumBuilder_ == null) {
          javaEnum_ = meetup.beeno.HDataTypes.JavaEnum.getDefaultInstance();
          onChanged();
        } else {
          javaEnumBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public meetup.beeno.HDataTypes.JavaEnum.Builder getJavaEnumBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getJavaEnumFieldBuilder().getBuilder();
      }
      public meetup.beeno.HDataTypes.JavaEnumOrBuilder getJavaEnumOrBuilder() {
        if (javaEnumBuilder_ != null) {
          return javaEnumBuilder_.getMessageOrBuilder();
        } else {
          return javaEnum_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.JavaEnum, meetup.beeno.HDataTypes.JavaEnum.Builder, meetup.beeno.HDataTypes.JavaEnumOrBuilder> 
          getJavaEnumFieldBuilder() {
        if (javaEnumBuilder_ == null) {
          javaEnumBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              meetup.beeno.HDataTypes.JavaEnum, meetup.beeno.HDataTypes.JavaEnum.Builder, meetup.beeno.HDataTypes.JavaEnumOrBuilder>(
                  javaEnum_,
                  getParentForChildren(),
                  isClean());
          javaEnum_ = null;
        }
        return javaEnumBuilder_;
      }
      
      // optional .hbase.StringList string_list = 9;
      private meetup.beeno.HDataTypes.StringList stringList_ = meetup.beeno.HDataTypes.StringList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.StringList, meetup.beeno.HDataTypes.StringList.Builder, meetup.beeno.HDataTypes.StringListOrBuilder> stringListBuilder_;
      public boolean hasStringList() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public meetup.beeno.HDataTypes.StringList getStringList() {
        if (stringListBuilder_ == null) {
          return stringList_;
        } else {
          return stringListBuilder_.getMessage();
        }
      }
      public Builder setStringList(meetup.beeno.HDataTypes.StringList value) {
        if (stringListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringList_ = value;
          onChanged();
        } else {
          stringListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setStringList(
          meetup.beeno.HDataTypes.StringList.Builder builderForValue) {
        if (stringListBuilder_ == null) {
          stringList_ = builderForValue.build();
          onChanged();
        } else {
          stringListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeStringList(meetup.beeno.HDataTypes.StringList value) {
        if (stringListBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              stringList_ != meetup.beeno.HDataTypes.StringList.getDefaultInstance()) {
            stringList_ =
              meetup.beeno.HDataTypes.StringList.newBuilder(stringList_).mergeFrom(value).buildPartial();
          } else {
            stringList_ = value;
          }
          onChanged();
        } else {
          stringListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearStringList() {
        if (stringListBuilder_ == null) {
          stringList_ = meetup.beeno.HDataTypes.StringList.getDefaultInstance();
          onChanged();
        } else {
          stringListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public meetup.beeno.HDataTypes.StringList.Builder getStringListBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getStringListFieldBuilder().getBuilder();
      }
      public meetup.beeno.HDataTypes.StringListOrBuilder getStringListOrBuilder() {
        if (stringListBuilder_ != null) {
          return stringListBuilder_.getMessageOrBuilder();
        } else {
          return stringList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          meetup.beeno.HDataTypes.StringList, meetup.beeno.HDataTypes.StringList.Builder, meetup.beeno.HDataTypes.StringListOrBuilder> 
          getStringListFieldBuilder() {
        if (stringListBuilder_ == null) {
          stringListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              meetup.beeno.HDataTypes.StringList, meetup.beeno.HDataTypes.StringList.Builder, meetup.beeno.HDataTypes.StringListOrBuilder>(
                  stringList_,
                  getParentForChildren(),
                  isClean());
          stringList_ = null;
        }
        return stringListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:hbase.HField)
    }
    
    static {
      defaultInstance = new HField(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:hbase.HField)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_DateTime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_DateTime_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_JavaEnum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_JavaEnum_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_StringList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_StringList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_HField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_HField_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datatypes.proto\022\005hbase\"/\n\010DateTime\022\021\n\t" +
      "timestamp\030\001 \002(\003\022\020\n\010timezone\030\002 \001(\t\"\'\n\010Jav" +
      "aEnum\022\014\n\004type\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\034\n\nSt" +
      "ringList\022\016\n\006values\030\001 \003(\t\"\330\002\n\006HField\022 \n\004t" +
      "ype\030\001 \002(\0162\022.hbase.HField.Type\022\014\n\004text\030\002 " +
      "\001(\t\022\017\n\007integer\030\003 \001(\003\022\r\n\005float\030\004 \001(\001\022\017\n\007b" +
      "oolean\030\005 \001(\010\022\016\n\006binary\030\006 \001(\014\022\"\n\tdate_tim" +
      "e\030\007 \001(\0132\017.hbase.DateTime\022\"\n\tjava_enum\030\010 " +
      "\001(\0132\017.hbase.JavaEnum\022&\n\013string_list\030\t \001(" +
      "\0132\021.hbase.StringList\"m\n\004Type\022\010\n\004TEXT\020\001\022\013",
      "\n\007INTEGER\020\002\022\t\n\005FLOAT\020\003\022\013\n\007BOOLEAN\020\004\022\n\n\006B" +
      "INARY\020\005\022\014\n\010DATETIME\020\006\022\014\n\010JAVAENUM\020\007\022\016\n\nS" +
      "TRINGLIST\020\010B\034\n\014meetup.beenoB\nHDataTypesH" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hbase_DateTime_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hbase_DateTime_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_DateTime_descriptor,
              new java.lang.String[] { "Timestamp", "Timezone", },
              meetup.beeno.HDataTypes.DateTime.class,
              meetup.beeno.HDataTypes.DateTime.Builder.class);
          internal_static_hbase_JavaEnum_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hbase_JavaEnum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_JavaEnum_descriptor,
              new java.lang.String[] { "Type", "Value", },
              meetup.beeno.HDataTypes.JavaEnum.class,
              meetup.beeno.HDataTypes.JavaEnum.Builder.class);
          internal_static_hbase_StringList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_hbase_StringList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_StringList_descriptor,
              new java.lang.String[] { "Values", },
              meetup.beeno.HDataTypes.StringList.class,
              meetup.beeno.HDataTypes.StringList.Builder.class);
          internal_static_hbase_HField_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_hbase_HField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_HField_descriptor,
              new java.lang.String[] { "Type", "Text", "Integer", "Float", "Boolean", "Binary", "DateTime", "JavaEnum", "StringList", },
              meetup.beeno.HDataTypes.HField.class,
              meetup.beeno.HDataTypes.HField.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
